SELECT
    int(idLobbyGame) AS idLobbyJogo,
    int(idPlayer) AS idJogador,
    int(idRoom) AS idSala,
    descMapName AS descNomeMapa,
    int(qtKill) AS qtAbates,
    int(qtAssist) AS qtdAssistencias,
    int(qtDeath) AS qtMortes,
    int(qtHs) AS qtHS,
    int(qtBombeDefuse) AS qtBombasDesarmadas,
    int(qtBombePlant) AS qtBombasArmadas,
    int(qtTk) AS qtAbateAmigo,
    int(qtTkAssist) AS qtAssistenciaAbateAmigo,
    int(qt1Kill) AS qt1AbateRound,
    int(qt2Kill) AS qt2AbateRound,
    int(qt3Kill) AS qt3AbateRound,
    int(qt4Kill) AS qt4AbateRound,
    int(qt5Kill) AS qt5AbateRound,
    int(qtPlusKill) AS qtMultiplosAbates,
    int(qtFirstKill) AS qtPrimeiroAbate,
    int(vlDamage) AS vlDano,
    int(qtHits) AS qtAcertos,
    int(qtShots) AS qtDisparos,
    int(qtLastAlive) AS qtUltimoSobrevivente,
    int(qtClutchWon) AS qtClutchsVencidos,
    int(qtRoundsPlayed) AS qtRoundsJogados,
    int(qtSurvived) AS qtRoundVivos,
    int(qtTrade) AS qtTrocaAbates,
    int(qtFlashAssist) AS qtAssistenciaFlash,
    int(qtHitHeadshot) AS qtAcertosCabeca,
    int(qtHitChest) AS qtAcertosPeito,
    int(qtHitStomach) AS qtAcertosEstomago,
    int(qtHitLeftAtm) AS qtAcertosBracoEsquerdo,
    int(qtHitRightArm) AS qtAcertosBracoDireito,
    int(qtHitLeftLeg) AS qtAcertosPernaEsquerda,
    int(qtHitRightLeg) AS qtAcertosPernaDireita,
    case when int(flWinner) = 1 then TRUE else FALSE end as flVitoria ,
    int(vlLevel) AS vlLevel,
    timestamp(dtCreatedAt) AS dtPartida

FROM bronze.gamersclub.tb_lobby_stats_player

